# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 454c968554faf3f61166727de8e7c442cfb35b0a786e2f700198e146e9e248880cabfae44fa393178f46d8a7e7a6282a5e3fa030eba062bbef52846fb42eee78

test:
  secret_key_base: 2be7969aaa717e6701a205c6e67b2d49ace7991a6836bb45302ab34e6a33eaa8354aa8f2513e5565af26f272ec06a8afbd913c7b16efc87f71edba3de226db5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
